/* CVS $Id: $ */
package com.epimorphics.vocabs; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/vocabs/xkos.ttl 
 * @author Auto-generated by schemagen on 12 Aug 2013 21:13 
 */
public class Xkos {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/linked-data/xkos#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Version 0.9.9.2 - 2012-10-21";
    
    public static final Property additionalContentNote = m_model.createProperty( "http://purl.org/linked-data/xkos#additionalContentNote" );
    
    public static final Property after = m_model.createProperty( "http://purl.org/linked-data/xkos#after" );
    
    public static final Property before = m_model.createProperty( "http://purl.org/linked-data/xkos#before" );
    
    public static final Property belongsTo = m_model.createProperty( "http://purl.org/linked-data/xkos#belongsTo" );
    
    public static final Property causal = m_model.createProperty( "http://purl.org/linked-data/xkos#causal" );
    
    public static final Property causedBy = m_model.createProperty( "http://purl.org/linked-data/xkos#causedBy" );
    
    public static final Property causes = m_model.createProperty( "http://purl.org/linked-data/xkos#causes" );
    
    public static final Property classifiedUnder = m_model.createProperty( "http://purl.org/linked-data/xkos#classifiedUnder" );
    
    public static final Property coreContentNote = m_model.createProperty( "http://purl.org/linked-data/xkos#coreContentNote" );
    
    public static final Property covers = m_model.createProperty( "http://purl.org/linked-data/xkos#covers" );
    
    public static final Property coversExhaustively = m_model.createProperty( "http://purl.org/linked-data/xkos#coversExhaustively" );
    
    public static final Property coversMutuallyExclusively = m_model.createProperty( "http://purl.org/linked-data/xkos#coversMutuallyExclusively" );
    
    public static final Property depth = m_model.createProperty( "http://purl.org/linked-data/xkos#depth" );
    
    public static final Property disjoint = m_model.createProperty( "http://purl.org/linked-data/xkos#disjoint" );
    
    public static final Property exclusionNote = m_model.createProperty( "http://purl.org/linked-data/xkos#exclusionNote" );
    
    /** <p>successeur dans la séquencesuccessor in the sequence</p> */
    public static final Property follows = m_model.createProperty( "http://purl.org/linked-data/xkos#follows" );
    
    public static final Property generalizes = m_model.createProperty( "http://purl.org/linked-data/xkos#generalizes" );
    
    public static final Property hasPart = m_model.createProperty( "http://purl.org/linked-data/xkos#hasPart" );
    
    public static final Property inclusionNote = m_model.createProperty( "http://purl.org/linked-data/xkos#inclusionNote" );
    
    public static final Property isPartOf = m_model.createProperty( "http://purl.org/linked-data/xkos#isPartOf" );
    
    public static final Property levels = m_model.createProperty( "http://purl.org/linked-data/xkos#levels" );
    
    public static final Property madeOf = m_model.createProperty( "http://purl.org/linked-data/xkos#madeOf" );
    
    public static final Property maxLength = m_model.createProperty( "http://purl.org/linked-data/xkos#maxLength" );
    
    /** <p>successeur immédiat dans la séquenceimmediate successor in the sequence</p> */
    public static final Property next = m_model.createProperty( "http://purl.org/linked-data/xkos#next" );
    
    public static final Property numberOfLevels = m_model.createProperty( "http://purl.org/linked-data/xkos#numberOfLevels" );
    
    public static final Property organizedBy = m_model.createProperty( "http://purl.org/linked-data/xkos#organizedBy" );
    
    /** <p>predecessor in the sequenceprédécesseur dans la séquence</p> */
    public static final Property precedes = m_model.createProperty( "http://purl.org/linked-data/xkos#precedes" );
    
    /** <p>immediate predecessor in the sequenceprédécesseur immédiat dans la séquence</p> */
    public static final Property previous = m_model.createProperty( "http://purl.org/linked-data/xkos#previous" );
    
    public static final Property sequential = m_model.createProperty( "http://purl.org/linked-data/xkos#sequential" );
    
    public static final Property sourceConcept = m_model.createProperty( "http://purl.org/linked-data/xkos#sourceConcept" );
    
    public static final Property specializes = m_model.createProperty( "http://purl.org/linked-data/xkos#specializes" );
    
    public static final Property succeeds = m_model.createProperty( "http://purl.org/linked-data/xkos#succeeds" );
    
    public static final Property supersedes = m_model.createProperty( "http://purl.org/linked-data/xkos#supersedes" );
    
    public static final Property targetConcept = m_model.createProperty( "http://purl.org/linked-data/xkos#targetConcept" );
    
    public static final Property temporal = m_model.createProperty( "http://purl.org/linked-data/xkos#temporal" );
    
    public static final Resource ClassificationLevel = m_model.createResource( "http://purl.org/linked-data/xkos#ClassificationLevel" );
    
    public static final Resource ConceptAssociation = m_model.createResource( "http://purl.org/linked-data/xkos#ConceptAssociation" );
    
    public static final Resource Correspondence = m_model.createResource( "http://purl.org/linked-data/xkos#Correspondence" );
    
}
